# Generated by Django 5.1.5 on 2025-02-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='avalability',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
